
# 星芽短剧
xydj:
  # 账号1:
  #   authorization: "123456"
  #   device_id: "123456"
  # 账号2:
  #   authorization: "123456"
  #   device_id: "123456"
    
# 霸王茶姬
bwcj: 
  #账号1:
    # cookie: "123456"
    # uid: "123456"
